### ISSUE TITLE
pnpm consistency and lockfile regeneration

### ISSUE THREAD

**Issue by matthewgalang** [brianlee1597/sf-social-club-member-portal#31]
I suspect resolving conflicts in a recent merge where we were simultaneously importing RTK on separate branches might be contributing to Vercel complaining. If anything, my guess would be to wipe the lock file and generate it again.

I also suspect using different pnpm versions could generate different lockfiles, so maybe we can configure that to be consistent.

**Comment by seanbrhn3** [comment]
Maybe add lock file to .gitignore?

**Comment by matthewgalang** [comment]
> You should always commit the lockfile (pnpm-lock.yaml).

https://pnpm.io/git#lockfiles
